### PR TITLE
build: add new flag "--enable-optimizations" and expand scope of "--enable-debug", additional homekeeping

### PR DESCRIPTION
**Pull request by kwvg**
## Additional information

This pull request is a result a comment which proposed a possible source for non-reproducible builds on Apple Silicon as difference in optimized code output.

While investigating further, it was realized that `bls-signatures` lacks the option to enable useful debugging flags or disable optimizations (both by the compiler and from libraries).

* `--enable-debug` will set `DEBUG=1` for Relic (existing behaviour), disables compiler optimization (and leaves library optimizations as-is), sets the dbginfo level to 3 and sets `-ftrapv`
* `--disable-optimizations` will disable _both_ compiler and library optimizations (by setting (`CPU_`)`ARCH` to `none` and setting the backend to `easy` unless overridden), does not change the dbginfo level and sets `-fwrapv`

If both flags are used and there are conflicts, the flags set by `--enable-debug` will take precedence (i.e. debug level will be 3 and `-ftrapv` will be set) 

These changes are made alongside general housekeeping and consolidation of the `autoconf` script.

### CODE REVIEW

**Comment by UdjinM6** [comment]
LGTM

>These changes are made alongside general housekeeping 

pls check 0d88e91 for more of this :)

**Review by UdjinM6 — APPROVED** [review]
LGTM, utACK 39791d4

(not sure why GH decided to put my approval here and not down below - I clearly pulled 39791d4 to review/compile 🤷‍♂️ )

**Review by knst — APPROVED** [review]
LGTM

**Review by PastaPastaPasta — APPROVED** [review]
light-utACK

**Pull request merged**
