### PR TITLE
build: commit relic-toolkit/relic@aecdcae to source tree as vendored

### PR DESCRIPTION
**Pull request by kittywhiskers**

### CODE REVIEW

**Review by PastaPastaPasta — DISMISSED** [review]
utACK for merging via merge commit

**Review by ogabrielides — DISMISSED** [review]
LGTM

**Review by ogabrielides — APPROVED** [review]
LGTM

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merge via merge commit

**Pull request merged**
