### PR TITLE
backport: Add some upstream PRs

### PR DESCRIPTION
**Pull request by xdustinface**
I noticed both `master` and `dash` branches are not really up do date with our latest release [v20181101](https://github.com/dashpay/bls-signatures/releases/tag/v20181101) and the latest upstream version before the lib restructuring [0.1.28](https://github.com/Chia-Network/bls-signatures/releases/tag/0.1.28) . So i added some missing PRs and one seperate commit (91b1ccd) to bring our working branch closer to them. I skipped some python binding changes of this PRs because we currently don't build/test them but that can be done later if there is any demand for it imo.  Also there are quite some more PRs missing but the ones i have in here now were the most useful ones for us. Let me know if there are others you want to see in here. 

@UdjinM6 i think it would be good if you could create a `develop` branch based on `dash` then we can merge this PR into `develop` and remove all branches besides `master` and `develop`?

### CODE REVIEW

**Review by UdjinM6 — DISMISSED** [review]
Backports looks good. Let's merge as is and deal with branches later.

utACK

**Review by UdjinM6 — APPROVED** [review]
I changed my mind (and the base branch :) )

re-utACK

**Comment by PastaPastaPasta** [comment]
Why not just rebase on their latest non-v2 version?

**Comment by xdustinface** [comment]
> Why not just rebase on their latest non-v2 version?

@PastaPastaPasta Didn't try how conflictual that would be + i didn't want to waste time with the Python bindings now i.e. i just focused on what we need for now to have the same as in our latest github release + what we need for the Go bindings. But feel free to do it in an other PR.

**Comment by PastaPastaPasta** [comment]
I think the idea should be that we want to maintain as small of a diff as absolutely possible, because none of us are true cryptographers. 

I'd really prefer the rebase method

**Comment by xdustinface** [comment]
> I think the idea should be that we want to maintain as small of a diff as absolutely possible

Well, thats the point of this PR.. having overall the least diff to get a branch matching our latest release + few useful other changes from upstream. Did you even try to review/look at the changes or compare the branches/releases? 

However, if you can come up with something better than this PR im happy to close it this one favour of your solution but i spent hours figuring out the differences between our `dash` branch, our latest release tag and chias latest v1 release tag and picking out what we really need in our branch so im done with it and don't want waste any more time with stuff we don't need at the moment.

> I'd really prefer the rebase method

Rebasing would end up in way more diff IMO and in adding code which we doesn't even need. Also, i might miss something there but reviewing the rebased branch would be weird to do and we would need to force push `develop`.

**Review by PastaPastaPasta — COMMENTED** [review]
What PR is 91b1ccd2ebb61f594e07325b93510e590e118053?

**Comment by xdustinface** [comment]
@PastaPastaPasta See initial description

> So i added some missing PRs and one seperate commit ([91b1ccd](https://github.com/dashpay/bls-signatures/commit/91b1ccd2ebb61f594e07325b93510e590e118053)) to bring our working branch closer to them. 

Its obviously a directly pushed commit.. i did at least not find a related PR.

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
