### PR TITLE
fix: dash is no more pretending being a 'libdashbls'

### PR DESCRIPTION
**Pull request by knst**
It resolves: https://github.com/dashpay/dash/issues/5270

It is still workaround but it should be more reliable.

### CODE REVIEW

**Review by kittywhiskers — APPROVED** [review]
utACK

**Comment by knst** [comment]
seems as CI broken: this PR has same broken tests: https://github.com/dashpay/bls-signatures/pull/75

**Comment by kittywhiskers** [comment]
The `17/27 checks OK` message seems to go as far back as https://github.com/dashpay/bls-signatures/pull/70, I'd say it'd go as back as https://github.com/dashpay/bls-signatures/pull/68 but https://github.com/dashpay/bls-signatures/pull/69 has only one test failure.

Failures relating to JS bindings seem to be a preexisting problem.

**Review by UdjinM6 — APPROVED** [review]
utACK, test failures look unrelated

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge

**Pull request merged**
