### PR TITLE
build: add barebones alternative build system support (GNU Autotools)

### PR DESCRIPTION
**Pull request by kittywhiskers**
Depends on https://github.com/dashpay/bls-signatures/pull/49

### CODE REVIEW

**Review by PastaPastaPasta — APPROVED** [review]
utACK for merging via merge commit

Seems fine to me, but I'm no auto tools expert :) I haven't compiled it locally, but am trusting CI. I think this has atomic and well described enough commits to justify a merge commit

**Review by UdjinM6 — CHANGES_REQUESTED** [review]

**Comment by UdjinM6** [comment]
also, I compiled with `./configure --with-backend=gmp-sec` and I'm getting this
```
$ ./runtest

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
runtest is a Catch v2.13.4 host application.
Run with -? for options

-------------------------------------------------------------------------------
class PrivateKey
  Copy {constructor|assignment operator}
-------------------------------------------------------------------------------
src/test.cpp:60
...............................................................................

src/test.cpp:70: FAILED:
  REQUIRE( pk2.GetG2Element().IsValid() )
with expansion:
  false

-------------------------------------------------------------------------------
IETF test vectors
  Pyecc vector
-------------------------------------------------------------------------------
src/test.cpp:320
...............................................................................

src/test.cpp:330: FAILED:
  REQUIRE( sig == G2Element::FromByteVector(sig1) )
due to unexpected exception with message:
  G2 element is invalid

-------------------------------------------------------------------------------
Chia test vectors
  Chia test vectors 1 (Basic)
-------------------------------------------------------------------------------
src/test.cpp:336
...............................................................................

src/test.cpp:358: FAILED:
  REQUIRE( Util::HexStr(sig1.Serialize()) == "b8faa6d6a3881c9fdbad803b170d70ca5cbf1e6ba5a586262df368c75acd1d1f" "fa3ab6ee21c71f844494659878f5eb230c958dd576b08b8564aad2ee0992e85a" "1e565f299cd53a285de729937f70dc176a1f01432129bb2b94d3d5031f8065a1" )
with expansion:
  "aa6202e531ce54bde8d0950c92b3917ba5d72553d3757d025dba9579df703f16c89736fd45b-
  2e9a23f11cdc8df68c8660dd84fc3960efc903edcfa30785921e2d17dde2af0bcfc382da755c-
  1bf05336e7c02080ebbcc386356244428027837c5"
  ==
  "b8faa6d6a3881c9fdbad803b170d70ca5cbf1e6ba5a586262df368c75acd1d1ffa3ab6ee21c-
  71f844494659878f5eb230c958dd576b08b8564aad2ee0992e85a1e565f299cd53a285de7299-
  37f70dc176a1f01432129bb2b94d3d5031f8065a1"

-------------------------------------------------------------------------------
Chia test vectors
  Chia test vector 2 (Augmented, aggregate of aggregates)
-------------------------------------------------------------------------------
src/test.cpp:404
...............................................................................

src/test.cpp:404: FAILED:
due to unexpected exception with message:
  Relic library error

-------------------------------------------------------------------------------
Chia test vectors
  Chia test vector 3 (PoP)
-------------------------------------------------------------------------------
src/test.cpp:439
...............................................................................

src/test.cpp:439: FAILED:
due to unexpected exception with message:
  Relic library error

Assertion failed: (ans.IsValid()), function FromMessage, file elements.cpp, line 330.
-------------------------------------------------------------------------------
Signature tests
  Should use copy constructor
-------------------------------------------------------------------------------
src/test.cpp:564
...............................................................................

src/test.cpp:564: FAILED:
due to a fatal error condition:
  SIGABRT - Abort (abnormal termination) signal

===============================================================================
test cases:   10 |    6 passed | 4 failed
assertions: 1215 | 1209 passed | 6 failed

zsh: abort      ./runtest
```

**Review by UdjinM6 — APPROVED** [review]
LGTM, ACK

unrelated to changes in this PR but https://github.com/dashpay/bls-signatures/actions/runs/3413163668/jobs/5679747776 (same as https://github.com/dashpay/bls-signatures/pull/43#issuecomment-1276577017)

**Review by PastaPastaPasta — APPROVED** [review]
utACK for squash merge (light ACK as I did build locally with auto tools)

**Pull request merged**
