### PR TITLE
feat(rust): allow to move G1 and G2 elements between threads

### PR DESCRIPTION
**Pull request by shumkov**
In Drive ABCI we would like to move elements between threads since they are part of validators set abstraction.
After the code expection it seems to me that we are safe to do that since G1 and G2 elements are immutable and we do not change internal state and do not keep refs in the other abstractions

### CODE REVIEW

**Review by ogabrielides — APPROVED** [review]
utACK. 
We should be fine, as immutability patterns on G1/G2Element _seem_ to be used.

**Review by UdjinM6 — DISMISSED** [review]
"C part not affected"-utACK 🤷‍♂️

**Review by ogabrielides — APPROVED** [review]
re-utACK

**Review by UdjinM6 — APPROVED** [review]
🤷‍♂️

**Pull request merged**
