### PR TITLE
src|test: Add `ExtendedPublicKey`, `ExtendedPrivateKey` and `ChainCode` 

### PR DESCRIPTION
**Pull request by xdustinface**
This adds slightly modified versions of the classes `ExtendedPublicKey`, `ExtendedPrivateKey` and `ChainCode` and the related tests from the previous lib versions like here https://github.com/dashpay/bls-signatures/tree/develop_0.1.

### CODE REVIEW

**Comment by UdjinM6** [comment]
Looks good but why not c96946d instead of b3d9b57?

**Review by UdjinM6 — APPROVED** [review]
utACK

**Review by UdjinM6 — APPROVED** [review]
re-utACK

**Review by PastaPastaPasta — APPROVED** [review]
utACK

**Pull request merged**
